<?php

use Illuminate\Database\Seeder;

class StoresTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('stores')->delete();

        DB::table('stores')->insert([
            ['id'=>'2389','store_name'=>'PT','store_country'=>'Aeroporto Lisboa AIRSIDE','store_area'=>'Portugal 2','store_segment'=>'Platinum','store_concept'=>'Intermediate ','address_id'=>'2389'],
            ['id'=>'2392','store_name'=>'PT','store_country'=>'Algarve Planta Alta ','store_area'=>'Portugal 2','store_segment'=>'Platinum','store_concept'=>'Intermediate ','address_id'=>'2392'],
            ['id'=>'2414','store_name'=>'ES','store_country'=>'ECI La Vaguada','store_area'=>'Madrid ','store_segment'=>'Gold','store_concept'=>'SIS 6000','address_id'=>'2414'],
            ['id'=>'2420','store_name'=>'ES','store_country'=>'Oasis','store_area'=>'Canarias','store_segment'=>'Platinum','store_concept'=>'2.0','address_id'=>'2420'],
            ['id'=>'2421','store_name'=>'ES','store_country'=>'Habaneras ','store_area'=>'Levante','store_segment'=>'Gold','store_concept'=>'Intermediate + RB SIS','address_id'=>'2421'],
            ['id'=>'2422','store_name'=>'ES','store_country'=>'Espai Girona','store_area'=>'Cataluña','store_segment'=>'Gold','store_concept'=>'Intermediate','address_id'=>'2422'],
            ['id'=>'2423','store_name'=>'ES','store_country'=>'Las Terrazas','store_area'=>'Canarias','store_segment'=>'Outlet','store_concept'=>'Intermediate','address_id'=>'2423'],
            ['id'=>'2428','store_name'=>'ES','store_country'=>'Aqua','store_area'=>'Levante ','store_segment'=>'Silver','store_concept'=>'Intermediate ','address_id'=>'2428'],
            ['id'=>'2430','store_name'=>'ES','store_country'=>'Vialia','store_area'=>'Andalucía','store_segment'=>'Silver','store_concept'=>'Intermediate','address_id'=>'2430'],
            ['id'=>'2431','store_name'=>'ES','store_country'=>"L'Aljub",'store_area'=>'Levante','store_segment'=>'Silver','store_concept'=>'2.0','address_id'=>'2431'],
            ['id'=>'2435','store_name'=>'ES','store_country'=>'Fañabe','store_area'=>'Canarias','store_segment'=>'Gold','store_concept'=>'Intermediate','address_id'=>'2435'],
            ['id'=>'2439','store_name'=>'ES','store_country'=>'Area Sur ','store_area'=>'Andalucía','store_segment'=>'Outlet','store_concept'=>'3.0 + RB SIS','address_id'=>'2439'],
            ['id'=>'2442','store_name'=>'ES','store_country'=>'Portal de la Marina','store_area'=>'Levante','store_segment'=>'Gold','store_concept'=>'Intermediate ','address_id'=>'2442'],
            ['id'=>'2443','store_name'=>'ES','store_country'=>'El Campanario','store_area'=>'Canarias','store_segment'=>'Gold','store_concept'=>'Basic','address_id'=>'2443'],
            ['id'=>'2451','store_name'=>'ES','store_country'=>'Getafe','store_area'=>'Madrid','store_segment'=>'Outlet','store_concept'=>'Intermediate ','address_id'=>'2451'],
            ['id'=>'2452','store_name'=>'ES','store_country'=>'Outletuy','store_area'=>'Madrid','store_segment'=>'Outlet','store_concept'=>'2.0 + RB SIS','address_id'=>'2452'],
            ['id'=>'2454','store_name'=>'ES','store_country'=>'Puerto Banús','store_area'=>'Andalucía','store_segment'=>'Platinum','store_concept'=>'3.0 + RB SIS','address_id'=>'2454'],
            ['id'=>'2455','store_name'=>'ES','store_country'=>'La Cañada','store_area'=>'Andalucía','store_segment'=>'Platinum','store_concept'=>'2.0','address_id'=>'2455'],
            ['id'=>'2461','store_name'=>'ES','store_country'=>'Plaza del Duque','store_area'=>'Canarias','store_segment'=>'Silver','store_concept'=>'2.0','address_id'=>'2461'],
            ['id'=>'2462','store_name'=>'ES','store_country'=>'Las Palmeras','store_area'=>'Canarias','store_segment'=>'Gold','store_concept'=>'Intermediate ','address_id'=>'2462'],
            ['id'=>'2463','store_name'=>'ES','store_country'=>'Mirador de Jinamar','store_area'=>'Canarias','store_segment'=>'Gold','store_concept'=>'Intermediate ','address_id'=>'2463'],
            ['id'=>'2464','store_name'=>'ES','store_country'=>'Bahía Sur','store_area'=>'Andalucía','store_segment'=>'Silver','store_concept'=>'Intermediate + RB SIS','address_id'=>'2464'],
            ['id'=>'2465','store_name'=>'ES','store_country'=>'Luz Shopping','store_area'=>'Andalucía','store_segment'=>'Outlet','store_concept'=>'Intermediate ','address_id'=>'2465'],
            ['id'=>'2466','store_name'=>'ES','store_country'=>'Rambla de Cataluña','store_area'=>'Cataluña','store_segment'=>'Platinum','store_concept'=>'6000 + RB SIS ','address_id'=>'2466'],
            ['id'=>'2470','store_name'=>'ES','store_country'=>'La Maquinista','store_area'=>'Cataluña','store_segment'=>'Silver','store_concept'=>'2.0','address_id'=>'2470'],
            ['id'=>'2472','store_name'=>'ES','store_country'=>'Mataró','store_area'=>'Cataluña','store_segment'=>'Gold','store_concept'=>'Intermediate','address_id'=>'2472'],
            ['id'=>'2474','store_name'=>'ES','store_country'=>'La Rinconada','store_area'=>'Andalucía','store_segment'=>'Outlet','store_concept'=>'Intermediate + 4.0 + RB SIS + Promo Table','address_id'=>'2474'],
            ['id'=>'2476','store_name'=>'ES','store_country'=>'Plaza Mayor','store_area'=>'Andalucía','store_segment'=>'Gold','store_concept'=>'Intermediate + RB SIS ','address_id'=>'2476'],
            ['id'=>'2477','store_name'=>'ES','store_country'=>'Diagonal Mar ','store_area'=>'Cataluña','store_segment'=>'Gold','store_concept'=>'Intermediate ','address_id'=>'2477'],
            ['id'=>'2478','store_name'=>'ES','store_country'=>'Las Rozas','store_area'=>'Madrid','store_segment'=>'Outlet','store_concept'=>'Intermediate','address_id'=>'2478'],
            ['id'=>'2479','store_name'=>'PT','store_country'=>'Factory Bonaire ','store_area'=>'Levante','store_segment'=>'Outlet','store_concept'=>'Intermediate + RB SIS + Promo Table','address_id'=>'2479'],
            ['id'=>'2481','store_name'=>'ES','store_country'=>'Artea','store_area'=>'Norte','store_segment'=>'Silver','store_concept'=>'2.0','address_id'=>'2481'],
            ['id'=>'2482','store_name'=>'ES','store_country'=>'La Morea','store_area'=>'Norte','store_segment'=>'Gold','store_concept'=>'Intermediate','address_id'=>'2482'],
            ['id'=>'2485','store_name'=>'ES','store_country'=>'Licenciado Pozas ','store_area'=>'Norte','store_segment'=>'Gold','store_concept'=>'6000 + RB SIS','address_id'=>'2485'],
            ['id'=>'2489','store_name'=>'ES','store_country'=>'Parque Principado','store_area'=>'Madrid','store_segment'=>'Gold','store_concept'=>'Intermediate ','address_id'=>'2489'],
            ['id'=>'2492','store_name'=>'ES','store_country'=>'Mirador ','store_area'=>'Canarias','store_segment'=>'Platinum','store_concept'=>'2.0 ','address_id'=>'2492'],
            ['id'=>'2493','store_name'=>'ES','store_country'=>'Fuencarral ','store_area'=>'Madrid','store_segment'=>'Platinum','store_concept'=>'6000 + RB SIS','address_id'=>'2493'],
            ['id'=>'2494','store_name'=>'ES','store_country'=>'Santa Cruz','store_area'=>'Canarias','store_segment'=>'Gold','store_concept'=>'Intermediate ','address_id'=>'2494'],
            ['id'=>'2495','store_name'=>'ES','store_country'=>'Dos Mares','store_area'=>'Levante','store_segment'=>'Gold','store_concept'=>'4.0 + RB SIS','address_id'=>'2495'],
            ['id'=>'2496','store_name'=>'ES','store_country'=>'Baricentro ','store_area'=>'Cataluña','store_segment'=>'Silver','store_concept'=>'Intermediate ','address_id'=>'2496'],
            ['id'=>'2497','store_name'=>'ES','store_country'=>'Dos Hermanas','store_area'=>'Andalucía','store_segment'=>'Outlet','store_concept'=>'Intermediate ','address_id'=>'2497'],
            ['id'=>'2499','store_name'=>'ES','store_country'=>'Valle Real','store_area'=>'Norte','store_segment'=>'Silver','store_concept'=>'2.0 Open Air','address_id'=>'2499'],
            ['id'=>'2507','store_name'=>'PT','store_country'=>'Dolce Vita Tejo Loja ','store_area'=>'Portugal 2','store_segment'=>'Silver','store_concept'=>'Intermediate ','address_id'=>'2507'],
            ['id'=>'2508','store_name'=>'PT','store_country'=>'Colombo','store_area'=>'Portugal 2','store_segment'=>'Platinum','store_concept'=>'2.0 + RB SIS + Promo table','address_id'=>'2508'],
            ['id'=>'2509','store_name'=>'PT','store_country'=>'Almada Forum ','store_area'=>'Portugal 1','store_segment'=>'Gold','store_concept'=>'Intermediate ','address_id'=>'2509'],
            ['id'=>'2517','store_name'=>'PT','store_country'=>'Norte Shopping','store_area'=>'Portugal 1','store_segment'=>'Platinum','store_concept'=>'3.0 + ZIGZAG (RB-OO)','address_id'=>'2517'],
            ['id'=>'2519','store_name'=>'PT','store_country'=>'Vasco Da Gama','store_area'=>'Portugal 1','store_segment'=>'Platinum','store_concept'=>'3.0 + ZIGZAG (RB-OO)','address_id'=>'2519'],
            ['id'=>'2521','store_name'=>'PT','store_country'=>'Braga Parque ','store_area'=>'Portugal 1','store_segment'=>'Gold','store_concept'=>'Intermediate + RB SIS','address_id'=>'2521'],
            ['id'=>'2532','store_name'=>'PT','store_country'=>'Cascais Shopping','store_area'=>'Portugal 1','store_segment'=>'Platinum','store_concept'=>'Intermediate ','address_id'=>'2532'],
            ['id'=>'2534','store_name'=>'PT','store_country'=>'Aeroporto Porto','store_area'=>'Portugal 2','store_segment'=>'Platinum','store_concept'=>'SIS 6000','address_id'=>'2534'],
            ['id'=>'2536','store_name'=>'PT','store_country'=>'Armazéns Chiado','store_area'=>'Portugal 1','store_segment'=>'Gold','store_concept'=>'4.0 + RB SIS','address_id'=>'2536'],
            ['id'=>'2539','store_name'=>'PT','store_country'=>'Campera Outlet ','store_area'=>'Portugal 1','store_segment'=>'Outlet','store_concept'=>'Intermediate ','address_id'=>'2539'],
            ['id'=>'2541','store_name'=>'PT','store_country'=>'Foz Plaza ','store_area'=>'Portugal 2','store_segment'=>'Silver','store_concept'=>'Intermediate','address_id'=>'2541'],
            ['id'=>'2545','store_name'=>'PT','store_country'=>'Forum Montijo','store_area'=>'Portugal 1','store_segment'=>'Silver','store_concept'=>'2.0 Open Air','address_id'=>'2545'],
            ['id'=>'2546','store_name'=>'PT','store_country'=>'Acores','store_area'=>'Portugal 2','store_segment'=>'Silver','store_concept'=>'2.0 Open Air','address_id'=>'2546'],
            ['id'=>'2547','store_name'=>'PT','store_country'=>'Outlet Freeport ','store_area'=>'Portugal 1','store_segment'=>'Outlet','store_concept'=>'2.0 + RB SIS + Promo Table','address_id'=>'2547'],
            ['id'=>'2548','store_name'=>'PT','store_country'=>'Dolce Vita Douro','store_area'=>'Portugal 2','store_segment'=>'Gold','store_concept'=>'Intermediate ','address_id'=>'2548'],
            ['id'=>'2549','store_name'=>'PT','store_country'=>'Vila Do Conde','store_area'=>'Portugal 1','store_segment'=>'Outlet','store_concept'=>'3.0 + RB SIS','address_id'=>'2549'],
            ['id'=>'2550','store_name'=>'PT','store_country'=>'Alma Shopping (Dolce Vita Coimbra)','store_area'=>'Portugal 2','store_segment'=>'Gold','store_concept'=>'3.0 + RB SIS','address_id'=>'2550'],
            ['id'=>'2552','store_name'=>'PT','store_country'=>'Alameda (Dolce Vita Antas)','store_area'=>'Portugal 2','store_segment'=>'Platinum','store_concept'=>'Intermediate ','address_id'=>'2552'],
            ['id'=>'2554','store_name'=>'PT','store_country'=>'Forum  Coimbra ','store_area'=>'Portugal 2','store_segment'=>'Gold','store_concept'=>'Intermediate + RB SIS','address_id'=>'2554'],
            ['id'=>'2556','store_name'=>'PT','store_country'=>'Arrabida Shopping ','store_area'=>'Portugal 2','store_segment'=>'Platinum','store_concept'=>'Intermediate ','address_id'=>'2556'],
            ['id'=>'2574','store_name'=>'PT','store_country'=>'Via Catarina','store_area'=>'Portugal 2','store_segment'=>'Gold','store_concept'=>'Intermediate','address_id'=>'2574'],
            ['id'=>'2575','store_name'=>'PT','store_country'=>'Mar Shopping','store_area'=>'Portugal 1','store_segment'=>'Silver','store_concept'=>'Intermediate ','address_id'=>'2575'],
            ['id'=>'2577','store_name'=>'PT','store_country'=>'Estacao Viana do Castelo ','store_area'=>'Portugal 1','store_segment'=>'Silver','store_concept'=>'3.0 + ZIGZAG (RB-OO)','address_id'=>'2577'],
            ['id'=>'2718','store_name'=>'ES','store_country'=>'Dehesa Vieja','store_area'=>'Madrid','store_segment'=>'Outlet','store_concept'=>'Intermediate ','address_id'=>'2718'],
            ['id'=>'2720','store_name'=>'PT','store_country'=>'Aeroporto Lisboa (LX)','store_area'=>'Portugal 2','store_segment'=>'Platinum','store_concept'=>'6000 + RB SIS ','address_id'=>'2720'],
            ['id'=>'2771','store_name'=>'ES','store_country'=>'ECI 3 de Mayo','store_area'=>'Canarias','store_segment'=>'Platinum','store_concept'=>'SIS 6000 + RB SIS','address_id'=>'2771'],
            ['id'=>'2772','store_name'=>'ES','store_country'=>'ECI Diagonal','store_area'=>'Cataluña','store_segment'=>'Platinum','store_concept'=>'4.0 + RB SIS','address_id'=>'2772'],
            ['id'=>'2773','store_name'=>'ES','store_country'=>'ECI Mesa y Lopez','store_area'=>'Canarias','store_segment'=>'Platinum','store_concept'=>'SIS 6000 + RB SIS','address_id'=>'2773'],
            ['id'=>'2774','store_name'=>'ES','store_country'=>'ECI 7 Palmas','store_area'=>'Canarias','store_segment'=>'Gold','store_concept'=>'SIS 6000','address_id'=>'2774'],
            ['id'=>'2784','store_name'=>'ES','store_country'=>'Sitges','store_area'=>'Cataluña','store_segment'=>'Platinum','store_concept'=>'6000 + RB SIS','address_id'=>'2784'],
            ['id'=>'2866','store_name'=>'ES','store_country'=>'Ricardo Soriano','store_area'=>'Andalucía','store_segment'=>'Gold','store_concept'=>'2.0','address_id'=>'2866'],
            ['id'=>'2967','store_name'=>'ES','store_country'=>'Aeropuerto BCN T1 Airside','store_area'=>'Cataluña','store_segment'=>'Platinum','store_concept'=>'3.0 ','address_id'=>'2967'],
            ['id'=>'2998','store_name'=>'ES','store_country'=>"L'illa",'store_area'=>'Cataluña','store_segment'=>'Platinum','store_concept'=>'2.0','address_id'=>'2998'],
            ['id'=>'2999','store_name'=>'ES','store_country'=>'Maremagnum','store_area'=>'Cataluña','store_segment'=>'Platinum','store_concept'=>'4.0 + RB SIS','address_id'=>'2999'],
            ['id'=>'3011','store_name'=>'ES','store_country'=>'Aeropuerto Alicante ','store_area'=>'Levante ','store_segment'=>'Platinum','store_concept'=>'2.0 + RB SIS','address_id'=>'3011'],
            ['id'=>'3012','store_name'=>'ES','store_country'=>'Aeropuerto Málaga Airside ','store_area'=>'Andalucía','store_segment'=>'Platinum','store_concept'=>'2.0 + RB SIS + Promo table','address_id'=>'3012'],
            ['id'=>'3060','store_name'=>'PT','store_country'=>'Dolce Vita Funchal','store_area'=>'Portugal 1','store_segment'=>'Silver','store_concept'=>'2.0 Open Air','address_id'=>'3060'],
            ['id'=>'3064','store_name'=>'ES','store_country'=>'Jaume III','store_area'=>'Baleares','store_segment'=>'Platinum','store_concept'=>'2.0 + RB SIS','address_id'=>'3064'],
            ['id'=>'3079','store_name'=>'ES','store_country'=>'Aeropuerto Fuerteventura ','store_area'=>'Canarias','store_segment'=>'Platinum','store_concept'=>'2.0 ','address_id'=>'3079'],
            ['id'=>'3093','store_name'=>'ES','store_country'=>'Aeropuerto Gran Canaria','store_area'=>'Canarias','store_segment'=>'Gold','store_concept'=>'2.0 ','address_id'=>'3093'],
            ['id'=>'3098','store_name'=>'ES','store_country'=>'Aeropuerto Ibiza ','store_area'=>'Baleares','store_segment'=>'Platinum','store_concept'=>'2.0 ','address_id'=>'3098'],
            ['id'=>'3102','store_name'=>'ES','store_country'=>'Aeropuerto Lanzarote','store_area'=>'Canarias','store_segment'=>'Gold','store_concept'=>'2.0 ','address_id'=>'3102'],
            ['id'=>'3103','store_name'=>'ES','store_country'=>'Aeropuerto Málaga Landside','store_area'=>'Andalucía','store_segment'=>'Platinum','store_concept'=>'2.0 + RB SIS','address_id'=>'3103'],
            ['id'=>'3117','store_name'=>'ES','store_country'=>'Aeropuerto Mahón Menorca ','store_area'=>'Baleares','store_segment'=>'Platinum','store_concept'=>'2.0 + 6000','address_id'=>'3117'],
            ['id'=>'3135','store_name'=>'ES','store_country'=>'Siam Mall','store_area'=>'Canarias','store_segment'=>'Platinum','store_concept'=>'4.0 + RB SIS','address_id'=>'3135'],
            ['id'=>'3140','store_name'=>'ES','store_country'=>'San Sebastian','store_area'=>'Norte','store_segment'=>'Platinum','store_concept'=>'2.0','address_id'=>'3140'],
            ['id'=>'3141','store_name'=>'ES','store_country'=>'Aeropuerto Tenerife Norte ','store_area'=>'Canarias','store_segment'=>'Gold','store_concept'=>'6000','address_id'=>'3141'],
            ['id'=>'3142','store_name'=>'ES','store_country'=>'Aeropuerto Tenerife Sur ','store_area'=>'Canarias','store_segment'=>'Gold','store_concept'=>'2.0','address_id'=>'3142'],
            ['id'=>'3176','store_name'=>'PT','store_country'=>'8 Avenida','store_area'=>'Portugal 3','store_segment'=>'Silver','store_concept'=>'Intermediate ','address_id'=>'3176'],
            ['id'=>'3177','store_name'=>'PT','store_country'=>'Amoreiras','store_area'=>'Portugal 1','store_segment'=>'Platinum','store_concept'=>'4.0 + RB SIS','address_id'=>'3177'],
            ['id'=>'3182','store_name'=>'PT','store_country'=>'Madeira Shopping','store_area'=>'Portugal 1','store_segment'=>'Gold','store_concept'=>'Intermediate ','address_id'=>'3182'],
            ['id'=>'3235','store_name'=>'ES','store_country'=>'ECI Campo de las Naciones','store_area'=>'Madrid','store_segment'=>'Gold','store_concept'=>'SIS 6000','address_id'=>'3235'],
            ['id'=>'3258','store_name'=>'ES','store_country'=>'Larios','store_area'=>'Andalucía','store_segment'=>'Platinum','store_concept'=>'2.0 + RB SIS','address_id'=>'3258'],
            ['id'=>'3575','store_name'=>'ES','store_country'=>'Factory Outlet Viladecans','store_area'=>'Cataluña','store_segment'=>'Outlet','store_concept'=>'2.0 + RB SIS + Promo Table','address_id'=>'3575'],
            ['id'=>'3768','store_name'=>'ES','store_country'=>'Cordoba / Gondomar','store_area'=>'Andalucía','store_segment'=>'Silver','store_concept'=>'2.0','address_id'=>'3768'],
            ['id'=>'3774','store_name'=>'ES','store_country'=>'Aeropuerto Palma de Mallorca Mod D','store_area'=>'Baleares','store_segment'=>'Platinum','store_concept'=>'2.0 ','address_id'=>'3774'],
            ['id'=>'3775','store_name'=>'ES','store_country'=>'Mallorca Fashion Outlet (Festival Park) ','store_area'=>'Baleares','store_segment'=>'Outlet','store_concept'=>'2.0','address_id'=>'3775'],
            ['id'=>'3778','store_name'=>'ES','store_country'=>'Bilbao Gran Vía','store_area'=>'Norte','store_segment'=>'Platinum','store_concept'=>'2.0','address_id'=>'3778'],
            ['id'=>'3907','store_name'=>'ES','store_country'=>'Las Rozas Village ','store_area'=>'Madrid','store_segment'=>'Outlet','store_concept'=>'4.0 + RB SIS','address_id'=>'3907'],
            ['id'=>'3908','store_name'=>'ES','store_country'=>'Gran Jonquera','store_area'=>'Cataluña','store_segment'=>'Outlet','store_concept'=>'2.0','address_id'=>'3908'],
            ['id'=>'3914','store_name'=>'ES','store_country'=>'Aeropuerto Madrid T4 LS','store_area'=>'Madrid ','store_segment'=>'Platinum','store_concept'=>'2.0','address_id'=>'3914'],
            ['id'=>'4193','store_name'=>'ES','store_country'=>'Aeropuerto Palma de Mallorca Mod A ','store_area'=>'Baleares','store_segment'=>'Platinum','store_concept'=>'2.0 + RB SIS + Promo Table','address_id'=>'4193'],
            ['id'=>'4243','store_name'=>'ES','store_country'=>'Serrano','store_area'=>'Madrid','store_segment'=>'Platinum','store_concept'=>'2.0','address_id'=>'4243'],
            ['id'=>'4290','store_name'=>'ES','store_country'=>'ECI Princesa','store_area'=>'Madrid','store_segment'=>'Gold ','store_concept'=>'SIS 6000','address_id'=>'4290'],
            ['id'=>'4298','store_name'=>'ES','store_country'=>'ECI Vigo','store_area'=>'Madrid','store_segment'=>'Gold','store_concept'=>'SIS 6000 + RB SIS','address_id'=>'4298'],
            ['id'=>'4477','store_name'=>'PT','store_country'=>'Rua Augusta','store_area'=>'Portugal 1','store_segment'=>'Platinum','store_concept'=>'3.0 + RB SIS ','address_id'=>'4477'],
            ['id'=>'4490','store_name'=>'ES','store_country'=>'Portaferrissa','store_area'=>'Cataluña','store_segment'=>'Platinum','store_concept'=>'2.0 + RB SIS','address_id'=>'4490'],
            ['id'=>'5031','store_name'=>'ES','store_country'=>'Recogidas','store_area'=>'Andalucía','store_segment'=>'Gold','store_concept'=>'2.0','address_id'=>'5031'],
            ['id'=>'5222','store_name'=>'PT','store_country'=>'Aeroporto Funchal','store_area'=>'Portugal 1','store_segment'=>'Platinum','store_concept'=>'Intermediate ','address_id'=>'5222'],
            ['id'=>'5272','store_name'=>'PT','store_country'=>'Leiria','store_area'=>'Portugal 2','store_segment'=>'Gold','store_concept'=>'2.0 Open Air','address_id'=>'5272'],
            ['id'=>'5329','store_name'=>'ES','store_country'=>'ECI Independencia ','store_area'=>'Madrid','store_segment'=>'Gold','store_concept'=>'SIS 6000','address_id'=>'5329'],
            ['id'=>'5364','store_name'=>'ES','store_country'=>'ECI Cornellá','store_area'=>'Cataluña','store_segment'=>'Gold','store_concept'=>'SIS 6000','address_id'=>'5364'],
            ['id'=>'5370','store_name'=>'ES','store_country'=>'ECI Badajoz Centro','store_area'=>'Madrid','store_segment'=>'Gold','store_concept'=>'SIS 6000','address_id'=>'5370'],
            ['id'=>'5396','store_name'=>'ES','store_country'=>'Aero Girona ','store_area'=>'Cataluña','store_segment'=>'Gold','store_concept'=>'SIS 6000','address_id'=>'5396'],
            ['id'=>'5466','store_name'=>'ES','store_country'=>'ECI Tarragona','store_area'=>'Cataluña','store_segment'=>'Gold','store_concept'=>'SIS 6000','address_id'=>'5466'],
            ['id'=>'5527','store_name'=>'ES','store_country'=>'ECI Valladolid','store_area'=>'Madrid','store_segment'=>'Gold','store_concept'=>'SIS 6000','address_id'=>'5527'],
            ['id'=>'5553','store_name'=>'ES','store_country'=>'ECI Puerto Banús','store_area'=>'Andalucía','store_segment'=>'Platinum','store_concept'=>'SIS 6000 + RB SIS','address_id'=>'5553'],
            ['id'=>'5554','store_name'=>'ES','store_country'=>'ECI Bahía de Cádiz','store_area'=>'Andalucía','store_segment'=>'Gold','store_concept'=>'SIS 6000','address_id'=>'5554'],
            ['id'=>'5620','store_name'=>'ES','store_country'=>'Juan de Austria','store_area'=>'Levante','store_segment'=>'Platinum','store_concept'=>'2.0','address_id'=>'5620'],
            ['id'=>'5650','store_name'=>'ES','store_country'=>'Málaga- Calle Granada','store_area'=>'Andalucía','store_segment'=>'Platinum','store_concept'=>'2.0 + RB SIS ','address_id'=>'5650'],
            ['id'=>'6541','store_name'=>'ES','store_country'=>'Portal del Angel (Flasghip)','store_area'=>'Cataluña','store_segment'=>'Platinum','store_concept'=>'Flagship + RB SIS','address_id'=>'6541'],
            ['id'=>'7035','store_name'=>'ES','store_country'=>'ECI Preciados','store_area'=>'Madrid','store_segment'=>'Platinum','store_concept'=>'SIS 2.0','address_id'=>'7035'],
            ['id'=>'7037','store_name'=>'ES','store_country'=>'ECI Palma de Mallorca','store_area'=>'Baleares','store_segment'=>'Platinum','store_concept'=>'4.0 + RB SIS','address_id'=>'7037'],
            ['id'=>'7039','store_name'=>'ES','store_country'=>'ECI Arabial','store_area'=>'Andalucía','store_segment'=>'Gold','store_concept'=>'SIS 6000','address_id'=>'7039'],
            ['id'=>'7044','store_name'=>'ES','store_country'=>'ECI Marineda','store_area'=>'Madrid ','store_segment'=>'Silver','store_concept'=>'SIS 6000','address_id'=>'7044'],
            ['id'=>'7065','store_name'=>'ES','store_country'=>'Aeropuerto Madrid T4 AS ','store_area'=>'Madrid ','store_segment'=>'Platinum','store_concept'=>'2.0 + 6000 +RB SIS','address_id'=>'7065'],
            ['id'=>'7068','store_name'=>'ES','store_country'=>'Calle Gambo','store_area'=>'Levante','store_segment'=>'Platinum','store_concept'=>'2.0','address_id'=>'7068'],
            ['id'=>'7069','store_name'=>'ES','store_country'=>'Las Arenas BCN ','store_area'=>'Cataluña','store_segment'=>'Platinum','store_concept'=>'2.0 + RB SIS','address_id'=>'7069'],
            ['id'=>'7700','store_name'=>'PT','store_country'=>'C.C. Nova Arcada','store_area'=>'Portugal 1','store_segment'=>'Gold','store_concept'=>'2.0','address_id'=>'7700'],
            ['id'=>'8593','store_name'=>'ES','store_country'=>'Logroño','store_area'=>'Norte','store_segment'=>'Gold','store_concept'=>'2.0','address_id'=>'8593'],
            ['id'=>'8596','store_name'=>'ES','store_country'=>'Jerez de la Frontera (Lancería)','store_area'=>'Andalucía','store_segment'=>'Silver','store_concept'=>'2.0','address_id'=>'8596'],
            ['id'=>'8597','store_name'=>'ES','store_country'=>'Columela ','store_area'=>'Andalucía','store_segment'=>'Gold','store_concept'=>'2.0 + RB SIS','address_id'=>'8597'],
            ['id'=>'8603','store_name'=>'ES','store_country'=>'Pamplona','store_area'=>'Norte','store_segment'=>'Gold','store_concept'=>'2.0 + ZIGZAG (RB-OO)','address_id'=>'8603'],
            ['id'=>'8606','store_name'=>'ES','store_country'=>'Santander','store_area'=>'Norte','store_segment'=>'Gold','store_concept'=>'2.0','address_id'=>'8606'],
            ['id'=>'8608','store_name'=>'ES','store_country'=>'Mahón ','store_area'=>'Baleares','store_segment'=>'Gold','store_concept'=>'2.0 ','address_id'=>'8608'],
            ['id'=>'8609','store_name'=>'ES','store_country'=>'Aeropuerto Palma de Mallorca Mod C','store_area'=>'Baleares','store_segment'=>'Platinum','store_concept'=>'3.0 + RB SIS','address_id'=>'8609'],
            ['id'=>'8777','store_name'=>'PT','store_country'=>'Aeroporto Faro (Loja)','store_area'=>'Portugal 2','store_segment'=>'Platinum','store_concept'=>'3.0','address_id'=>'8777'],
            ['id'=>'8778','store_name'=>'PT','store_country'=>'Aeroporto Faro Kiosko','store_area'=>'Portugal 2','store_segment'=>'Platinum','store_concept'=>'3.0 Special','address_id'=>'8778'],
            ['id'=>'8779','store_name'=>'PT','store_country'=>'Aeroporto Lisboa T2','store_area'=>'Portugal 2','store_segment'=>'Platinum','store_concept'=>'3.0 + RB SIS','address_id'=>'8779'],
            ['id'=>'8910','store_name'=>'ES','store_country'=>'Aeropuerto Madrid T2','store_area'=>'Madrid','store_segment'=>'Platinum','store_concept'=>'3.0 + RB SIS','address_id'=>'8910'],
            ['id'=>'8993','store_name'=>'ES','store_country'=>'Aeropuerto MAD T3','store_area'=>'Madrid ','store_segment'=>'Platinum','store_concept'=>'3.0 + RB SIS','address_id'=>'8993'],
            ['id'=>'9060','store_name'=>'ES ','store_country'=>'Tetuan','store_area'=>'Andalucía','store_segment'=>'Platinum','store_concept'=>'4.0 + RB SIS','address_id'=>'9060'],
            ['id'=>'9081','store_name'=>'ES','store_country'=>'Barakaldo Fashion Outlet','store_area'=>'Norte','store_segment'=>'Outlet','store_concept'=>'Intermediate ','address_id'=>'9081'],
            ['id'=>'9082','store_name'=>'ES','store_country'=>'Coruña The Style Outlet','store_area'=>'Madrid','store_segment'=>'Outlet','store_concept'=>'Intermediate ','address_id'=>'9082'],
            ['id'=>'9128','store_name'=>'ES','store_country'=>'Gandía','store_area'=>'Levante','store_segment'=>'Silver','store_concept'=>'3.0 + RB SIS','address_id'=>'9128'],
            ['id'=>'9137','store_name'=>'ES','store_country'=>'Murcia Gran Vía','store_area'=>'Levante','store_segment'=>'Gold','store_concept'=>'Intermediate + RB SIS + 4.0','address_id'=>'9137'],
            ['id'=>'9140','store_name'=>'PT','store_country'=>'Rua do Carmo ','store_area'=>'Portugal 1','store_segment'=>'Platinum','store_concept'=>'3.0 + ZIGZAG (RB-OO)','address_id'=>'9140'],
            ['id'=>'9141','store_name'=>'ES','store_country'=>'Aeropuerto Bilbao','store_area'=>'Norte','store_segment'=>'Platinum','store_concept'=>'3.0 + RB SIS','address_id'=>'9141'],
            ['id'=>'9142','store_name'=>'ES','store_country'=>'Jaume II','store_area'=>'Baleares','store_segment'=>'Platinum','store_concept'=>'3.0 + RB SIS','address_id'=>'9142'],
            ['id'=>'9159','store_name'=>'ES','store_country'=>'Plaza Sant Jaume','store_area'=>'Cataluña','store_segment'=>'Platinum','store_concept'=>'3.0 + ZIGZAG (RB-OO)','address_id'=>'9159'],
            ['id'=>'9160','store_name'=>'ES','store_country'=>'El Muelle','store_area'=>'Canarias','store_segment'=>'Silver','store_concept'=>'3.0 + ZIGZAG (RB-OO)','address_id'=>'9160'],
            ['id'=>'9166','store_name'=>'ES','store_country'=>'Aeropuerto Valencia','store_area'=>'Levante','store_segment'=>'Platinum','store_concept'=>'3.0 + RB SIS','address_id'=>'9166'],
            ['id'=>'9167','store_name'=>'ES','store_country'=>'Aeropuerto Santiago','store_area'=>'Norte','store_segment'=>'Platinum','store_concept'=>'3.0 + RB SIS ','address_id'=>'9167'],
            ['id'=>'9192','store_name'=>'ES','store_country'=>'Aeropuerto BCN T1 No Schengen','store_area'=>'Cataluña','store_segment'=>'Platinum','store_concept'=>'3.0 + RB SIS','address_id'=>'9192'],
            ['id'=>'9193','store_name'=>'PT','store_country'=>'Algarve Outlet Inter Ikea','store_area'=>'Portugal 2','store_segment'=>'Outlet','store_concept'=>'3.0 + ZIGZAG (RB-OO)','address_id'=>'9193'],
            ['id'=>'9194','store_name'=>'PT','store_country'=>'Povoa','store_area'=>'Portugal 1','store_segment'=>'Gold','store_concept'=>'3.0 + RB SIS ','address_id'=>'9194'],
            ['id'=>'9195','store_name'=>'ES','store_country'=>'Algeciras','store_area'=>'Andalucía','store_segment'=>'Gold','store_concept'=>'3.0 + RB SIS ','address_id'=>'9195'],
            ['id'=>'9206','store_name'=>'ES','store_country'=>'Denia','store_area'=>'Levante','store_segment'=>'Platinum','store_concept'=>'3.0 + RB SIS','address_id'=>'9206'],
            ['id'=>'9276','store_name'=>'PT','store_country'=>'Strada Outlet','store_area'=>'Portugal 2','store_segment'=>'Outlet','store_concept'=>'SGH-NXT + RB SIS','address_id'=>'9276'],
            ['id'=>'9281','store_name'=>'ES','store_country'=>'Outlet alicante','store_area'=>'Levante','store_segment'=>'Outlet','store_concept'=>'3.0 + RB SIS','address_id'=>'9281'],
            ['id'=>'9328','store_name'=>'ES','store_country'=>'Puigcerdá','store_area'=>'Cataluña','store_segment'=>'Gold','store_concept'=>'3.0 + RB SIS ','address_id'=>'9328'],
            ['id'=>'9347','store_name'=>'ES','store_country'=>'La Roca Village ','store_area'=>'Cataluña','store_segment'=>'Outlet','store_concept'=>'4.0 + RB SIS','address_id'=>'9347'],
            ['id'=>'9348','store_name'=>'ES','store_country'=>'Aero BCN T1 Airside Schengen (exAristocrazy)','store_area'=>'Cataluña','store_segment'=>'Platinum','store_concept'=>'3.0 + RB SIS','address_id'=>'9348'],
            ['id'=>'9530','store_name'=>'ES','store_country'=>'Finestrelles','store_area'=>'Cataluña','store_segment'=>'Platinum','store_concept'=>'4.0 + RB SIS','address_id'=>'9530'],
        ]);
    }
}
